services:
  - type: web
    name: physics-rss-aggregator
    env: python
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /
    autoDeploy: true
