name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests (if any)
        run: |
          echo "Running basic checks..."
          python -c "import app; print('App imports successfully')"
      
      - name: Trigger Render Deploy
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK" ]; then
            echo "Triggering Render deployment..."
            curl -X POST "$RENDER_DEPLOY_HOOK"
          else
            echo "RENDER_DEPLOY_HOOK not set. Skipping deployment."
            echo "Please set up a Render web service and add the deploy hook to repository secrets."
          fi
      
      - name: Deployment status
        run: |
          echo "Deployment triggered. Check Render dashboard for status."
          echo "Application will be available at your Render URL once deployed."
